<link href="{{ asset('dist-front/css/animate.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/bootstrap.min.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/font-awesome.min.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/magnific-popup.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/owl.carousel.min.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist/css/iziToast.min.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/global.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/style.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/responsive.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('dist-front/css/spacing.css') }}" type="text/css" rel="stylesheet">